### ISSUE TITLE
Allow script arguments

### ISSUE THREAD

**Issue by LarsKumbier** [adhocteam/script_exporter#6]
I've written an abstract shell script to check for statuspage.io-results. However, I am unable to add arguments to the script like so:

```
## config.yml
scripts:
  - name: bitbucket-ssh
    script: /bin/check-statuspage-io.sh "https://bqlf8qjztdtr.statuspage.io/api/v2/components.json" "SSH"
```

This results in an error code 127 (command not found). I've managed with writing shell wrappers, but it would be nice to have be able to run shell commands with arguments.

**Comment by mmukherjee** [comment]
Hi Lars,

Not sure if I am able to replicate your use case, but I am able to use a config file with params
```
scripts:
  - name: Login_Monitor_ABC_SYST
    script: ./ABC_login_syst.sh TestAutomation
    timeout: 120

  - name: Login_Monitor_Finacle_SBX
    script: ./ABC_login_syst.sh TestAutomation2
    timeout: 120
```
the ABC_login_syst.sh expects the parameter as $1
