### ISSUE TITLE
Prometheus configs

### ISSUE THREAD

**Issue by mmukherjee** [adhocteam/script_exporter#7]
Hi,

Quite a basic question I guess, but I am struggling to get this working with prometheus. My prometheus.yml file is as follows -

```
  - job_name: 'login_job'
    static_configs:
      - targets:
        - http://127.0.0.1:9172/probe?name=Login_Monitor_ABC_SYST
        - http://127.0.0.1:9172/probe?name=Login_Monitor_ABC_SBX
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9172
```
**What is working**
When I access the URL - 'http://127.0.0.1:9172/probe?name=Login_Monitor_ABC_SYST', it executes the script and returns the status code and duration 
```
# curl http://127.0.0.1:9172/probe?name=Login_Monitor_ABC_SYST
script_duration_seconds{script="Login_Monitor_ABC_SYST"} 81.698242
script_success{script="Login_Monitor_ABC_SYST"} 1
```
**What is not working**
I would expect prometheus to hit this URL when it scrapes it. I do see successful scrape metrics in prometheus, but its not hitting this URL, and thus not executing my script.

What am I missing?

**Comment by mrpity** [comment]
I resolved it the following way:
'metrics_path' and 'params' were added in  section 'job':
example:
`
  - job_name: "test-script-exporter"
    metrics_path: "/probe"
    params:
        pattern: ['.*']
    static_configs:
    - targets:
        - "localhost:9172"
` 

This is equivalent to: `http://localhost:9172/probe?pattern=.*`
Maybe it helps you. Also look at: https://prometheus.io/docs/operating/configuration/

**Comment by wtip** [comment]
you're using the targets incorrectly and the rebabel config needs to be adjusted
```
  - job_name: 'login_job'
    static_configs:
      - targets:
        - Login_Monitor_ABC_SYST
        - Login_Monitor_ABC_SBX
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_name
      - source_labels: [__param_name]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9172
```

**Comment by devsschmidt** [comment]
Hi,

i've tried to apply your suggested configuration but i dont receive the "script_success" metric in Prometheus.

requesting the exporter metrics via curl works 
```
$ curl myhost:9172/probe?name=my_script_1
script_duration_seconds{script="my_script_1"} 0.003117
script_success{script="my_script_1"} 1 
```

my prometheus configuration

```
  - job_name: 'status.backup'
    static_configs:
      - targets:
        - my_script_1
        - my_script_2
        - my_script_3
        - my_script_4
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_name
      - source_labels: [__param_name]
        target_label: instance
      - target_label: __address__
        replacement: myhost:9172
```

i still get metrics about the targets like 

```
script_exporter_build_info{branch="master",goversion="go1.7.4",instance="my_script_1",job="status.backup",revision="32f32c8479653966c277de64c976b327a257dfbf",version="1.0.2"}	1
script_exporter_build_info{branch="master",goversion="go1.7.4",instance="my_script_2",job="status.backup",revision="32f32c8479653966c277de64c976b327a257dfbf",version="1.0.2"}	1
script_exporter_build_info{branch="master",goversion="go1.7.4",instance="my_script_3",job="status.backup",revision="32f32c8479653966c277de64c976b327a257dfbf",version="1.0.2"}	1
script_exporter_build_info{branch="master",goversion="go1.7.4",instance="my_script_4",job="status.backup",revision="32f32c8479653966c277de64c976b327a257dfbf",version="1.0.2"}
```

how can i retrive the script_success metric?

**Comment by matheusfigueredo** [comment]
I have the same error :(

@wtip  I don't understand why I need to put into `targets` my scripts names (I would like to use `pattern=.*`) and how to monitoring many hosts with this logic.

My prometheus file is as follow:

```yaml
- job_name: 'script_exporter'
  static_configs: 
    - targets: ['192.168.0.1', '192.168.0.2']
```

I was trying use `metrics_path` like `/probe?pattern=.*` to run all my scripts but doesn't work this config :(

Any help?

**Comment by matheusfigueredo** [comment]
I change my `scrape_configs` and works for me.

```yaml
- job_name: 'script_exporter'
  metrics_path: /probe
  params:
    pattern: ['.*']
  static_configs: 
    - targets: ['192.168.0.1', '192.168.0.2']
```

So, @devsschmidt maybe you will need to do this:

```yaml
- job_name: 'status.backup-Login_Monitor_ABC_SYST'
  static_configs:
    - targets: ['127.0.0.1:9172']
  params:
    name: ['Login_Monitor_ABC_SYST']
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9172
```

```yaml
- job_name: 'status.backup-Login_Monitor_ABC_SBX'
  static_configs:
    - targets: ['127.0.0.1:9172']
  params:
    name: ['Login_Monitor_ABC_SBX']
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9172
```

Good luck :)
